# Generated by Django 6.1 on 2026-09-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('FR', 'FR'), ('SR', 'SR')], max_length=2)),
                ('number', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_date', models.DateField()),
            ],
            options={
                'indexes': [models.Index(fields=['business_date', 'entry_type'], name='entries_ent_busines_098bcf_idx'), models.Index(fields=['created_at'], name='entries_ent_created_823464_idx')],
            },
        ),
    ]
