# Generated by Django 6.1 on 2026-09-03 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_entry_owner'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='entry',
            new_name='entries_ent_owner_i_f9d1a2_idx',
            old_name='entries_ent_owner_i_5d6a12_idx',
        ),
    ]
